services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false  --ISCAgent false
    restart: always
    ports: 
      - 51773:1972
      - 52773:52772
      - 53773
    volumes:
      - ./:/irisdev/app
 
  ecpclient:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false  --ISCAgent false
    restart: always
    ports: 
      - 41773:1972
      - 42773:52772
      - 53773
    volumes:
      - ./:/irisdev/app
